// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzzpkdaaewrpaaaaudmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6enBrZGFhZXdycGFhYWF1ZG1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNDE2ODAsImV4cCI6MjA2MTkxNzY4MH0.wOZ3pTo7dFZ3QgfoNk8ClWHQoyRlmmdovc-WsplECY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);